In [30]:
import pandas as pd
import altair as alt
import numpy as np

Reading Data

In [31]:
df = pd.read_csv('analysis_dataset.csv')
df

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct
0,0.000000,1362275028,869,u:gonc,en,es,822ef52ef2cf0f095a65190d10958517,salt/salt<n><sg>,2,2,1,0
1,1.000000,1363007578,63128,u:b8co,de,en,e83432c98b3619a933438e9300467491,wasser/wasser<n><nt><sg><acc>,28,27,3,3
2,1.000000,1363039865,13125,u:jcDT,fr,en,65675f993b9cdc38918837f561a70625,l'/le<det><def><mf><sg>,5,4,1,1
3,1.000000,1362767513,358897,u:h7S0,es,en,e03faef7df59e95e2d78e7baf3095ac4,blancas/blanco<adj><f><pl>,5,5,1,1
4,0.666667,1362659556,632,u:hjZY,en,it,0a7ad985b6b19b5cfb4723f207220a3d,they/prpers<prn><subj><p3><mf><pl>,32,30,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.000000,1362719204,7736865,u:eok6,en,pt,103f6339b11202f32c1340b9fda6c56b,june/june<n><sg>,4,4,1,1
9996,0.000000,1362677031,443290,u:heiK,es,en,b8030c6502ec62329c3aba482d31e7d8,departamento/departamento<n><m><sg>,3,2,1,0
9997,1.000000,1362095331,1713,u:hBBg,en,es,822ef52ef2cf0f095a65190d10958517,salt/salt<n><sg>,9,8,1,1
9998,1.000000,1362496528,1550797,u:fKX_,es,en,bc66ddd0ffa3ade2ce5bae4ac1e7bf92,<*sf>/juez<n><m><*numb>,1,1,1,1
9999,0.000000,1362847188,537468,u:6AU,it,en,05a8f41784dc70931794e826ff27441e,succo/succo<n><m><sg>,3,3,1,0

In [32]:
df['history_accuracy'] = df['history_correct'] / df['history_seen'] # Creating new metrics/column
df

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct,history_accuracy
0,0.000000,1362275028,869,u:gonc,en,es,822ef52ef2cf0f095a65190d10958517,salt/salt<n><sg>,2,2,1,0,1.000000
1,1.000000,1363007578,63128,u:b8co,de,en,e83432c98b3619a933438e9300467491,wasser/wasser<n><nt><sg><acc>,28,27,3,3,0.964286
2,1.000000,1363039865,13125,u:jcDT,fr,en,65675f993b9cdc38918837f561a70625,l'/le<det><def><mf><sg>,5,4,1,1,0.800000
3,1.000000,1362767513,358897,u:h7S0,es,en,e03faef7df59e95e2d78e7baf3095ac4,blancas/blanco<adj><f><pl>,5,5,1,1,1.000000
4,0.666667,1362659556,632,u:hjZY,en,it,0a7ad985b6b19b5cfb4723f207220a3d,they/prpers<prn><subj><p3><mf><pl>,32,30,3,2,0.937500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.000000,1362719204,7736865,u:eok6,en,pt,103f6339b11202f32c1340b9fda6c56b,june/june<n><sg>,4,4,1,1,1.000000
9996,0.000000,1362677031,443290,u:heiK,es,en,b8030c6502ec62329c3aba482d31e7d8,departamento/departamento<n><m><sg>,3,2,1,0,0.666667
9997,1.000000,1362095331,1713,u:hBBg,en,es,822ef52ef2cf0f095a65190d10958517,salt/salt<n><sg>,9,8,1,1,0.888889
9998,1.000000,1362496528,1550797,u:fKX_,es,en,bc66ddd0ffa3ade2ce5bae4ac1e7bf92,<*sf>/juez<n><m><*numb>,1,1,1,1,1.000000
9999,0.000000,1362847188,537468,u:6AU,it,en,05a8f41784dc70931794e826ff27441e,succo/succo<n><m><sg>,3,3,1,0,1.000000

In [33]:
sampled_df = df.sample(n=min(5000, len(df)), random_state=42)
len(sampled_df)
sampled_df

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct,history_accuracy
6252,1.0,1362835317,396542,u:iQf4,de,en,7f79fc712e91f1e703bb5f805ab74e8a,diät/diät<n><f><sg><*case>,1,1,1,1,1.000000
4684,1.0,1362280404,6711,u:h6Xq,en,es,5a4b5fe1ab77078da6c5bfddbf0e81af,touch/touch<vblex><pres>,3,3,1,1,1.000000
1731,0.6,1362601721,2416416,u:fThc,de,en,7f78970589f8a9fe95bca610215c051a,ein/ein<det><ind><nt><sg><acc>,32,28,5,3,0.875000
4742,1.0,1362091769,1059,u:grsV,es,en,88d32763695c33d85f3e8af4bb09b6ee,araña/araña<n><f><sg>,6,6,1,1,1.000000
4521,1.0,1362199770,492,u:e1Qx,en,pt,928787744a962cd4ec55c1b22cedc913,eats/eat<vblex><pri><p3><sg>,96,83,4,4,0.864583
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5743,1.0,1362589666,79633,u:ipcH,en,es,099dfb07f4ace185b82838c1fb5781ff,sugar/sugar<n><sg>,1,1,2,2,1.000000
6226,1.0,1362169849,1837,u:igr-,en,es,fe1c2edd8cfeedbbbfafc42448e957c9,spider/spider<n><sg>,37,37,2,2,1.000000
1973,1.0,1362219579,186193,u:iCsG,it,en,a916c869fb9122e370b265b88d3bc1b1,burro/burro<n><m><sg>,5,5,1,1,1.000000
336,1.0,1362776222,4360,u:iLyM,es,en,4bdb859f599fa07dd5eecdab0acc2d34,a/a<pr>,6,5,1,1,0.833333
2764,1.0,1362888731,293014,u:iR-s,fr,en,8f1dc808b41b08007d5e66978fd78a4d,mange/manger<vblex><pri><p3><sg>,19,18,1,1,0.947368

Analyzing differences in historical learning performance across learning languages based on UI language
* maybe we need to relook the newly created column - richy

In [37]:
chart = alt.Chart(sampled_df).mark_boxplot().encode(
    x=alt.X('learning_language:N', title='Learning Language'),
    y=alt.Y('history_accuracy:Q', title='Accuracy'),
).properties(
    title='Historical Accuracy VS Language being Learned'
)

chart.display() # hmmm this chart lowkey might be useless lol - richy

alt.Chart(...)

As learners encounter the same vocabulary item more times historically, does their current-session recall improve?

In [54]:
# History Bins
bins = sampled_df.copy()
# Group encounters in the current session
bins['history_group'] = pd.cut(
    bins['history_seen'],
    bins=[0, 4, 9, 19, 49, float("inf")],
    labels=['1–4', '5–9', '10–19', '20–49', '50+']
)

In [58]:
line = alt.Chart(bins).mark_line().encode(
    x=alt.X('history_group:O',
            sort = ['1–4', '5–9', '10–19', '20–49', '50+'],
            title='History Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Precision'),
).properties(
    title='Average Recall by History Seen',
    width=500,
    height=300
)

point = alt.Chart(bins).mark_point().encode(
    x=alt.X('history_group:O',
            sort = ['1–4', '5–9', '10–19', '20–49', '50+'],
            title='History Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Precision'),
).properties(
    title='Average Recall by History Seen',
    width=500,
    height=300
)

overlay = point + line
overlay.display()

alt.LayerChart(...)

Does repeated exposure to a vocabulary item within the current session correspond with higher recall?

In [60]:
# Session Bins
bins = sampled_df.copy()
# Group encounters in the current session
bins['session_group'] = pd.cut(
    bins['session_seen'],
    bins=[0, 1, 2, 3, 4, float('inf')],
    labels=['1', '2', '3', '4', '5+']
)

In [66]:
line = alt.Chart(bins).mark_line().encode(
    x=alt.X('session_group:O',
            sort = ['1', '2', '3', '4', '5+'],
            title='Session Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Precision'),
).properties(
    title='Average Recall vs Session Seen',
    width=500,
    height=300
)

point = alt.Chart(bins).mark_point().encode(
    x=alt.X('session_group:O',
            sort = ['1', '2', '3', '4', '5+'],
            title='Session Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Precision'),
).properties(
    title='Average Recall vs Session Seen',
    width=500,
    height=300
)

combined = point + line
combined.display()

alt.LayerChart(...)