In [9]:
import pandas as pd
import altair as alt
import numpy as np

Reading Data

In [10]:
df = pd.read_csv('analysis_dataset.csv')
df.head()

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct
0,0.0,1362434189,342767,u:_6K,en,es,b974624f112084b39586380fe4aaf32a,man/man<n><sg>,16,14,1,0
1,1.0,1362698937,106662,u:i2TA,en,es,928787744a962cd4ec55c1b22cedc913,eats/eat<vblex><pri><p3><sg>,5,3,3,3
2,1.0,1362210918,51859,u:iIYs,es,en,22e3fc5f089cf47dae927dfddcce2844,ellos/prpers<prn><tn><p3><m><pl>,8,8,1,1
3,1.0,1362347852,3610438,u:gQ71,es,en,f9d3186a3a829083942aa09a75d1aae6,leen/leer<vblex><pri><p3><pl>,2,2,1,1
4,0.5,1362870047,581551,u:iLj2,en,es,c76d36f47e394429d9c14d2088e4a85c,phase/phase<n><sg>,3,3,2,1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   p_recall           5000 non-null   float64
 1   timestamp          5000 non-null   int64
 2   delta              5000 non-null   int64
 3   user_id            5000 non-null   object
 4   learning_language  5000 non-null   object
 5   ui_language        5000 non-null   object
 6   lexeme_id          5000 non-null   object
 7   lexeme_string      5000 non-null   object
 8   history_seen       5000 non-null   int64
 9   history_correct    5000 non-null   int64
 10  session_seen       5000 non-null   int64
 11  session_correct    5000 non-null   int64
dtypes: float64(1), int64(6), object(5)
memory usage: 468.9+ KB

In [12]:
df.describe()

,p_recall,timestamp,delta,history_seen,history_correct,session_seen,session_correct
count,5000.000000,5.000000e+03,5.000000e+03,5000.00000,5000.00000,5000.000000,5000.000000
mean,0.890519,1.362586e+09,7.678062e+05,24.47760,21.70040,1.777400,1.599600
std,0.280194,2.914586e+05,2.408921e+06,143.04737,126.89792,1.280069,1.248836
min,0.000000,1.362083e+09,2.000000e+00,1.00000,1.00000,1.000000,0.000000
25%,1.000000,1.362340e+09,5.350000e+02,3.00000,3.00000,1.000000,1.000000
50%,1.000000,1.362588e+09,7.882200e+04,6.00000,6.00000,1.000000,1.000000
75%,1.000000,1.362842e+09,4.747660e+05,15.00000,13.00000,2.000000,2.000000
max,1.000000,1.363105e+09,3.170928e+07,5657.00000,5370.00000,16.000000,16.000000

In [13]:
df['history_accuracy'] = df['history_correct'] / df['history_seen'] # Creating new metrics/column
df.head()

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct,history_accuracy
0,0.0,1362434189,342767,u:_6K,en,es,b974624f112084b39586380fe4aaf32a,man/man<n><sg>,16,14,1,0,0.875
1,1.0,1362698937,106662,u:i2TA,en,es,928787744a962cd4ec55c1b22cedc913,eats/eat<vblex><pri><p3><sg>,5,3,3,3,0.600
2,1.0,1362210918,51859,u:iIYs,es,en,22e3fc5f089cf47dae927dfddcce2844,ellos/prpers<prn><tn><p3><m><pl>,8,8,1,1,1.000
3,1.0,1362347852,3610438,u:gQ71,es,en,f9d3186a3a829083942aa09a75d1aae6,leen/leer<vblex><pri><p3><pl>,2,2,1,1,1.000
4,0.5,1362870047,581551,u:iLj2,en,es,c76d36f47e394429d9c14d2088e4a85c,phase/phase<n><sg>,3,3,2,1,1.000

Analyzing differences in historical learning performance across learning languages based on UI language
* maybe we need to relook the newly created column - richy

In [14]:
chart = alt.Chart(df).mark_bar().encode(
    x=alt.X('learning_language:N', title='Learning Language'),
    y=alt.Y('mean(history_accuracy):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Mean Historical Accuracy'),
    color=alt.Color('learning_language:N'),
    tooltip=alt.Tooltip('mean(history_accuracy):Q', format='.2f')
).properties(
    title='Mean Historical Accuracy VS Language being Learned'
)
chart

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

<VegaLite 5 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/display_frontends.html#troubleshooting

As learners encounter the same vocabulary item more times historically, does their current-session recall improve?

In [15]:
# History Bins
bins = df.copy()

bins['history_group'] = pd.cut(
    bins['history_seen'],
    bins=[0, 4, 9, 19, 49, float("inf")],
    labels=['1–4', '5–9', '10–19', '20–49', '50+']
)

In [16]:
languages = sorted(bins['learning_language'].unique())
languages

['de', 'en', 'es', 'fr', 'it', 'pt']

In [17]:
lang_dropdown = alt.binding_select(options=[None, 'de', 'en', 'es', 'fr', 'it', 'pt'],
                                   labels=['All', 'German', 'English', 'Spanish', 'French', 'Italian', 'Portuguese'],
                                   name='Learning Language: ')
lang_select = alt.selection_point(fields=['learning_language'], bind=lang_dropdown)

line = alt.Chart(bins).mark_line().encode(
    x=alt.X('history_group:O',
            sort = ['1–4', '5–9', '10–19', '20–49', '50+'],
            title='History Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(zero=False, nice=True, padding=20),
            axis=alt.Axis(format='.0%'),
            title='Average Recall')
).add_params(
    lang_select
).transform_filter(
    lang_select
).properties(
    title='Average Recall by History Seen',
    width=500,
    height=300
)

point = alt.Chart(bins).mark_point().encode(
    x=alt.X('history_group:O',
            sort = ['1–4', '5–9', '10–19', '20–49', '50+'],
            title='History Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(zero=False, nice=True, padding=20),
            axis=alt.Axis(format='.0%'),
            title='Average Recall')
).transform_filter(
    lang_select
).properties(
    title='Average Recall by History Seen',
    width=500,
    height=300
)

overlay = point + line
overlay.display()

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

<VegaLite 5 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/display_frontends.html#troubleshooting

Does repeated exposure to a vocabulary item within the current session correspond with higher recall?

In [18]:
# Session Bins
bins = df.copy()

bins['session_group'] = pd.cut(
    bins['session_seen'],
    bins=[0, 1, 2, 3, 4, float('inf')],
    labels=['1', '2', '3', '4', '5+']
)

In [19]:
line = alt.Chart(bins).mark_line().encode(
    x=alt.X('session_group:O',
            sort = ['1', '2', '3', '4', '5+'],
            title='Session Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Average Recall'),
).properties(
    title='Average Recall vs Session Seen',
    width=500,
    height=300
)

point = alt.Chart(bins).mark_point().encode(
    x=alt.X('session_group:O',
            sort = ['1', '2', '3', '4', '5+'],
            title='Session Seen'),
    y=alt.Y('mean(p_recall):Q',
            scale=alt.Scale(domain=[0.85, 0.95], zero=False),
            axis=alt.Axis(format='.0%'),
            title='Average Recall'),
).properties(
    title='Average Recall vs Session Seen',
    width=500,
    height=300
)

combined = point + line
combined.display()

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

<VegaLite 5 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/display_frontends.html#troubleshooting